services:
  - type: web
    name: dol-wage-level-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
